# font
font_size 16.0

# cursor
cursor_shape block
shell_integration no-cursor

# window
window_border_width            1pt
hide_window_decorations        titlebar-only
window_padding_width           5
remember_window_size           yes
# disable :: ... on menubar of macos
macos_show_window_title_in     none

# THEME BEGIN
include    Tokyo-Night.conf

# BEGIN work if background image is none
background_opacity    0.8
background_blur       64
# END work if background image is none

# BEGIN background image
background_image          12-Dark.jpg
background_image_layout   cscaled
background_image_linear   yes
background_tint_gaps      0.8
background_tint           0.7
# END background image

# THEME END

# tab bar
tab_bar_edge                   top
tab_bar_style                  powerline
tab_powerline_style            slanted
tab_bar_min_tabs               1
# tab_separator                  " ┃ "
tab_title_template             "{index}.{title}"

# mouse action

detect_urls no

copy_on_select clipboard

# remove \n at the end of the line smartly
strip_trailing_spaces smart

select_by_word_characters ${}/&@_.

# when mouse move to a window, cursor focus on this window automaticlly
# focus_follows_mouse yes

mouse_map right press grabbed,ungrabbed no-op
mouse_map right click grabbed,ungrabbed paste_from_clipboard

allow_hyperlinks no


# layouts
enabled_layouts stack,tall,horizontal,vertical

# cursor animation
cursor_trail 3
cursor_trail_decay 0.1 0.4
# cursor_trail_color none

# key mapping
macos_option_as_alt yes

map cmd+t        launch --type=tab --cwd=current zsh -c "fastfetch --config ~/.config/fastfetch/config.jsonc; exec zsh"
map cmd+w        close_tab
map cmd+shift+i  set_tab_title
map cmd+1        goto_tab               1
map cmd+2        goto_tab               2
map cmd+3        goto_tab               3
map cmd+4        goto_tab               4
map cmd+5        goto_tab               5
map cmd+6        goto_tab               6
map cmd+7        goto_tab               7
map cmd+8        goto_tab               8
map cmd+9        goto_tab               9
map cmd+0        goto_tab              10
map cmd+p        goto_tab              -1

map ctrl+shift+enter launch --type=window --cwd=current
map ctrl+shift+w     close_window
map ctrl+shift+r     start_resizing_window

map ctrl+shift+up    resize_window taller
map ctrl+shift+down  resize_window shorter
map ctrl+shift+right resize_window wider
map ctrl+shift+left  resize_window narrower

map ctrl+shift+j     next_window
map ctrl+shift+k     previous_window

map ctrl+shift+m     swap_with_window

map cmd+shift+l      next_layout

# ssh
share_connections yes

# macos quit
macos_quit_when_last_window_closed yes


